async function ortWasmThreaded(moduleArg={}){var moduleRtn;var g=moduleArg,aa=!!globalThis.window,h=!!globalThis.WorkerGlobalScope,m=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type,n=h&&self.name?.startsWith("em-pthread");if(m){const {createRequire:a}=await import("module");var require=a(import.meta.url),ba=require("worker_threads");global.Worker=ba.Worker;n=(h=!ba.V)&&"em-pthread"==ba.workerData}g.mountExternalData=(a,b)=>{a.startsWith("./")&&(a=a.substring(2));(g.o||(g.o=new Map)).set(a,b)};
g.unmountExternalData=()=>{delete g.o};var SharedArrayBuffer=globalThis.SharedArrayBuffer??(new WebAssembly.Memory({initial:0,maximum:0,shared:!0})).buffer.constructor,ca="./this.program",da=(a,b)=>{throw b;},ea=import.meta.url,fa="",ha,ia;
if(m){var fs=require("fs");ea.startsWith("file:")&&(fa=require("path").dirname(require("url").fileURLToPath(ea))+"/");ia=a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a)};ha=async a=>{a=ja(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);da=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||h){try{fa=(new URL(".",ea)).href}catch{}m||(h&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";
b.send(null);return new Uint8Array(b.response)}),ha=async a=>{if(ja(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);})}var ka=console.log.bind(console),la=console.error.bind(console);
if(m){var ma=require("util"),na=a=>"object"==typeof a?ma.inspect(a):a;ka=(...a)=>fs.writeSync(1,a.map(na).join(" ")+"\n");la=(...a)=>fs.writeSync(2,a.map(na).join(" ")+"\n")}var oa=ka,q=la,r,t,pa=!1,u,ja=a=>a.startsWith("file://");function v(){w.buffer!=x.buffer&&qa()}var ra,sa;
if(m&&n){var ta=ba.parentPort;ta.on("message",a=>global.onmessage?.({data:a}));Object.assign(globalThis,{self:global,postMessage:a=>ta.postMessage(a)});process.on("uncaughtException",a=>{postMessage({i:"uncaughtException",error:a});process.exit(1)})}var ua;
if(n){var va=!1;self.onunhandledrejection=b=>{throw b.reason||b;};async function a(b){try{var c=b.data,d=c.i;if("load"===d){let e=[];self.onmessage=f=>e.push(f);ua=()=>{postMessage({i:"loaded"});for(let f of e)a(f);self.onmessage=a};for(const f of c.H)if(!g[f]||g[f].proxy)g[f]=(...k)=>{postMessage({i:"callHandler",G:f,args:k})},"print"==f&&(oa=g[f]),"printErr"==f&&(q=g[f]);w=c.P;qa();t=c.R;wa();xa()}else if("run"===d){ya(c.h);za(c.h,0,0,1,0,0);Aa();Ba(c.h);va||(Ca(),va=!0);try{await Da(c.N,c.u)}catch(e){if("unwind"!=
e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?va&&Ea():d&&(q(`worker: received unknown command ${d}`),q(c)))}catch(e){throw Fa(),e;}}self.onmessage=a}var x,y,A,B,C,D,Ga,E,F,Ha,Ia=!1;function qa(){var a=w.buffer;g.HEAP8=x=new Int8Array(a);A=new Int16Array(a);g.HEAPU8=y=new Uint8Array(a);B=new Uint16Array(a);g.HEAP32=C=new Int32Array(a);g.HEAPU32=D=new Uint32Array(a);Ga=new Float32Array(a);E=new Float64Array(a);F=new BigInt64Array(a);Ha=new BigUint64Array(a)}
function Ja(){Ia=!0;n?ua():G.__wasm_call_ctors()}function Ka(a){a="Aborted("+a+")";q(a);pa=!0;a+=". Build with -sASSERTIONS for more info.";Ia&&La();a=new WebAssembly.RuntimeError(a);sa?.(a);throw a;}var Ma;async function Na(a){if(!r)try{var b=await ha(a);return new Uint8Array(b)}catch{}if(a==Ma&&r)a=new Uint8Array(r);else if(ia)a=ia(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Oa(a,b){try{var c=await Na(a);return await WebAssembly.instantiate(c,b)}catch(d){q(`failed to asynchronously prepare wasm: ${d}`),Ka(d)}}async function Pa(a){var b=Ma;if(!r&&!ja(b)&&!m)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){q(`wasm streaming compile failed: ${d}`),q("falling back to ArrayBuffer instantiation")}return Oa(b,a)}
function Qa(){H={HaveOffsetConverter:Ra,__pthread_create_js:Sa,__syscall_fcntl64:Ta,__syscall_fstat64:Ua,__syscall_getcwd:Wa,__syscall_getdents64:Xa,__syscall_ioctl:Ya,__syscall_lstat64:Za,__syscall_mkdirat:$a,__syscall_newfstatat:ab,__syscall_openat:bb,__syscall_readlinkat:cb,__syscall_rmdir:db,__syscall_stat64:eb,__syscall_unlinkat:fb,_abort_js:gb,_embind_register_bigint:hb,_embind_register_bool:ib,_embind_register_emval:jb,_embind_register_float:kb,_embind_register_integer:lb,_embind_register_memory_view:mb,
_embind_register_std_string:nb,_embind_register_std_wstring:ob,_embind_register_void:pb,_emscripten_init_main_thread_js:qb,_emscripten_notify_mailbox_postmessage:rb,_emscripten_receive_on_main_thread_js:sb,_emscripten_runtime_keepalive_clear:tb,_emscripten_thread_cleanup:ub,_emscripten_thread_mailbox_await:Ba,_emscripten_thread_set_strongref:vb,_emval_await:wb,_emval_create_invoker:xb,_emval_decref:yb,_emval_equals:zb,_emval_get_global:Ab,_emval_get_module_property:Bb,_emval_get_property:Cb,_emval_incref:Db,
_emval_invoke:Eb,_emval_invoke_i64:Fb,_emval_new_array:Gb,_emval_new_array_from_memory_view:Hb,_emval_new_cstring:Ib,_emval_new_object:Jb,_emval_run_destructors:Kb,_emval_set_property:Lb,_gmtime_js:Mb,_localtime_js:Nb,_mktime_js:Ob,_mmap_js:Pb,_munmap_js:Qb,_setitimer_js:Rb,_tzset_js:Sb,clock_time_get:Tb,emscripten_asm_const_int:Ub,emscripten_asm_const_ptr:Vb,emscripten_check_blocking_allowed:Wb,emscripten_date_now:Xb,emscripten_errn:Yb,emscripten_exit_with_live_runtime:Zb,emscripten_get_heap_max:$b,
emscripten_get_now:ac,emscripten_num_logical_cores:bc,emscripten_pc_get_function:cc,emscripten_resize_heap:dc,emscripten_stack_snapshot:ec,emscripten_stack_unwind_buffer:fc,environ_get:gc,environ_sizes_get:hc,exit:ic,fd_close:jc,fd_read:kc,fd_seek:lc,fd_write:mc,memory:w,proc_exit:nc};if(!H.F){H.F=!0;var a=H,b=/^(invoke_.*|__asyncjs__.*)$/;for(let [c,d]of Object.entries(a))"function"==typeof d&&(d.J||b.test(c))&&(a[c]=d=new WebAssembly.Suspending(d))}return{env:H,wasi_snapshot_preview1:H}}
async function wa(){function a(d,e){d=G=d.exports;var f=/^(OrtAppendExecutionProvider|OrtCreateSession|OrtRun|OrtRunWithBinding|OrtBindInput|main|__main_argc_argv)$/;oc=new Set;var k={};for(let [l,p]of Object.entries(d))"function"==typeof p?(f.test(l)&&(oc.add(p),p=WebAssembly.promising(p)),k[l]=pc(p)):k[l]=p;G=k;G=qc();rc.push(G._emscripten_tls_init);d=G;sc=d.__getTypeName;Ca=d._embind_initialize_bindings;g._OrtInit=d.OrtInit;g._OrtGetLastError=d.OrtGetLastError;g._OrtCreateSessionOptions=d.OrtCreateSessionOptions;
g._OrtAppendExecutionProvider=d.OrtAppendExecutionProvider;g._OrtAddFreeDimensionOverride=d.OrtAddFreeDimensionOverride;g._OrtAddSessionConfigEntry=d.OrtAddSessionConfigEntry;g._OrtReleaseSessionOptions=d.OrtReleaseSessionOptions;g._OrtCreateSession=d.OrtCreateSession;g._OrtReleaseSession=d.OrtReleaseSession;g._OrtGetInputOutputCount=d.OrtGetInputOutputCount;g._OrtGetInputOutputMetadata=d.OrtGetInputOutputMetadata;g._OrtFree=d.OrtFree;g._OrtCreateTensor=d.OrtCreateTensor;g._OrtGetTensorData=d.OrtGetTensorData;
g._OrtReleaseTensor=d.OrtReleaseTensor;g._OrtCreateRunOptions=d.OrtCreateRunOptions;g._OrtAddRunConfigEntry=d.OrtAddRunConfigEntry;g._OrtReleaseRunOptions=d.OrtReleaseRunOptions;g._OrtCreateBinding=d.OrtCreateBinding;g._OrtBindInput=d.OrtBindInput;g._OrtBindOutput=d.OrtBindOutput;g._OrtClearBoundOutputs=d.OrtClearBoundOutputs;g._OrtReleaseBinding=d.OrtReleaseBinding;g._OrtRunWithBinding=d.OrtRunWithBinding;g._OrtRun=d.OrtRun;g._OrtEndProfiling=d.OrtEndProfiling;tc=d.pthread_self;I=g._free=d.free;
uc=g._malloc=d.malloc;za=d._emscripten_thread_init;Fa=d._emscripten_thread_crashed;vc=d._emscripten_run_js_on_main_thread;wc=d._emscripten_thread_free_data;xc=d._emscripten_thread_exit;yc=d._emscripten_timeout;zc=d._emscripten_check_mailbox;La=d.__trap;Ac=d.emscripten_stack_set_limits;Bc=d._emscripten_stack_restore;Cc=d._emscripten_stack_alloc;Dc=d.emscripten_stack_get_current;Ec=d.__indirect_function_table;t=e;return G}var b=Qa();if(g.instantiateWasm)return new Promise(d=>{g.instantiateWasm(b,(e,
f)=>{d(a(e,f))})});if(n){var c=new WebAssembly.Instance(t,Qa());return a(c,t)}Ma??=g.locateFile?g.locateFile?g.locateFile("ort-wasm-simd-threaded.jspi.wasm",fa):fa+"ort-wasm-simd-threaded.jspi.wasm":(new URL("ort-wasm-simd-threaded.jspi.wasm",import.meta.url)).href;return function(d){return a(d.instance,d.module)}(await Pa(b))}class Fc{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Gc=a=>{a.terminate();a.onmessage=()=>{}},Ic=()=>{for(var a=Hc;0<a.length;)a.shift()(g)},Hc=[],J=0,K=null,Lc=a=>{0==L.length&&(Jc(),Kc(L[0]));var b=L.pop();if(!b)return 6;M.push(b);N[a.h]=b;b.h=a.h;var c={i:"run",N:a.M,u:a.u,h:a.h};m&&b.unref();b.postMessage(c,a.B);return 0},O=0,P=(a,b,...c)=>{var d=16*c.length,e=Dc(),f=Cc(d),k=f>>>3,l;for(l of c)"bigint"==typeof l?((v(),F)[k++>>>0]=1n,(v(),F)[k++>>>0]=l):((v(),F)[k++>>>0]=0n,(v(),E)[k++>>>0]=l);a=vc(a,0,d,f,b);Bc(e);return a};
function nc(a){if(n)return P(0,1,a);u=a;if(!(0<O)){for(var b of M)Gc(b);for(b of L)Gc(b);L=[];M=[];N={};pa=!0}da(a,new Fc(a))}function Mc(a){if(n)return P(1,0,a);ic(a)}var ic=a=>{u=a;if(n)throw Mc(a),"unwind";nc(a)},L=[],M=[],rc=[],N={};function Nc(){for(var a=g.numThreads-1;a--;)Jc();Hc.push(async()=>{var b=Oc();J++;await b;J--;0==J&&K&&(b=K,K=null,b())})}var Pc=a=>{var b=a.h;delete N[b];L.push(a);M.splice(M.indexOf(a),1);a.h=0;wc(b)};function Aa(){rc.forEach(a=>a())}
var Kc=a=>new Promise(b=>{a.onmessage=f=>{var k=f.data;f=k.i;if(k.s&&k.s!=tc()){var l=N[k.s];l?l.postMessage(k,k.B):q(`Internal error! Worker sent a message "${f}" to target pthread ${k.s}, but that thread no longer exists!`)}else if("checkMailbox"===f)Ea();else if("spawnThread"===f)Lc(k);else if("cleanupThread"===f)Qc(()=>{Pc(N[k.O])});else if("loaded"===f)a.loaded=!0,m&&!a.h&&a.unref(),b(a);else if("setimmediate"===k.target)a.postMessage(k);else if("uncaughtException"===f)a.onerror(k.error);else if("callHandler"===
f)g[k.G](...k.args);else f&&q(`worker sent an unknown command ${f}`)};a.onerror=f=>{q(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};m&&(a.on("message",f=>a.onmessage({data:f})),a.on("error",f=>a.onerror(f)));var c=[],d=[],e;for(e of d)g.propertyIsEnumerable(e)&&c.push(e);a.postMessage({i:"load",H:c,P:w,R:t})});async function Oc(){if(!n)return Promise.all(L.map(Kc))}
function Jc(){var a=new Worker(new URL(import.meta.url),{type:"module",workerData:"em-pthread",name:"em-pthread"});L.push(a)}function ya(a){var b=(v(),D)[a+52>>>2>>>0];a=(v(),D)[a+56>>>2>>>0];Ac(b,b-a);Bc(b)}var Rc=[],Da=async(a,b)=>{O=0;var c=WebAssembly,d=c.promising,e=Rc[a];e||(Rc[a]=e=Ec.get(a),oc?.has(e)&&(Rc[a]=e=WebAssembly.promising(e)));a=d.call(c,e)(b);a=await a;0<O?u=a:xc(a)},w;function Sc(a,b,c,d){return n?P(2,1,a,b,c,d):Sa(a,b,c,d)}
function Sa(a,b,c,d){a>>>=0;b>>>=0;c>>>=0;d>>>=0;if(!globalThis.SharedArrayBuffer)return 6;var e=[];if(n&&0===e.length)return Sc(a,b,c,d);a={M:c,h:a,u:d,B:e};return n?(a.i="spawnThread",postMessage(a,e),0):Lc(a)}
var Tc=globalThis.TextDecoder&&new TextDecoder,Uc=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},Vc=(a,b=0,c,d)=>{b>>>=0;c=Uc(a,b,c,d);if(16<c-b&&a.buffer&&Tc)return Tc.decode(a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Wc=(a,b,c)=>(a>>>=0)?Vc((v(),y),a,b,c):"";function Ta(a,b,c){return n?P(3,1,a,b,c):0}function Ua(a,b){if(n)return P(4,1,a,b)}function Wa(a,b){if(n)return P(5,1,a,b)}function Xa(a,b,c){if(n)return P(6,1,a,b,c)}function Ya(a,b,c){return n?P(7,1,a,b,c):0}function Za(a,b){if(n)return P(8,1,a,b)}function $a(a,b,c){if(n)return P(9,1,a,b,c)}function ab(a,b,c,d){if(n)return P(10,1,a,b,c,d)}function bb(a,b,c,d){if(n)return P(11,1,a,b,c,d)}
function cb(a,b,c,d){if(n)return P(12,1,a,b,c,d)}function db(a){if(n)return P(13,1,a)}function eb(a,b){if(n)return P(14,1,a,b)}function fb(a,b,c){if(n)return P(15,1,a,b,c)}var gb=()=>Ka(""),R=a=>{a>>>=0;for(var b="";;){var c=(v(),y)[a++>>>0];if(!c)return b;b+=String.fromCharCode(c)}},Xc={},Yc={},Zc={},S=class extends Error{constructor(a){super(a);this.name="BindingError"}};
function $c(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(Yc.hasOwnProperty(a)){if(c.I)return;throw new S(`Cannot register type '${d}' twice`);}Yc[a]=b;delete Zc[a];Xc.hasOwnProperty(a)&&(b=Xc[a],delete Xc[a],b.forEach(e=>e()))}function T(a,b,c={}){return $c(a,b,c)}
var ad=(a,b,c)=>{switch(b){case 1:return c?d=>(v(),x)[d>>>0]:d=>(v(),y)[d>>>0];case 2:return c?d=>(v(),A)[d>>>1>>>0]:d=>(v(),B)[d>>>1>>>0];case 4:return c?d=>(v(),C)[d>>>2>>>0]:d=>(v(),D)[d>>>2>>>0];case 8:return c?d=>(v(),F)[d>>>3>>>0]:d=>(v(),Ha)[d>>>3>>>0];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}};
function hb(a,b,c,d,e){a>>>=0;c>>>=0;b=R(b>>>0);d=0n===d;let f=k=>k;if(d){const k=8*c;f=l=>BigInt.asUintN(k,l);e=f(e)}T(a,{name:b,g:f,l:(k,l)=>{"number"==typeof l&&(l=BigInt(l));return l},j:ad(b,c,!d),m:null})}function ib(a,b,c,d){a>>>=0;b=R(b>>>0);T(a,{name:b,g:function(e){return!!e},l:function(e,f){return f?c:d},j:function(e){return this.g((v(),y)[e>>>0])},m:null})}var bd=[],U=[0,1,,1,null,1,!0,1,!1,1];function yb(a){a>>>=0;9<a&&0===--U[a+1]&&(U[a]=void 0,bd.push(a))}
var V=a=>{if(!a)throw new S(`Cannot use deleted val. handle = ${a}`);return U[a]},W=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=bd.pop()||U.length;U[b]=a;U[b+1]=1;return b}};function cd(a){return this.g((v(),D)[a>>>2>>>0])}var dd={name:"emscripten::val",g:a=>{var b=V(a);yb(a);return b},l:(a,b)=>W(b),j:cd,m:null};function jb(a){return T(a>>>0,dd)}
var ed=(a,b)=>{switch(b){case 4:return function(c){return this.g((v(),Ga)[c>>>2>>>0])};case 8:return function(c){return this.g((v(),E)[c>>>3>>>0])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}};function kb(a,b,c){a>>>=0;c>>>=0;b=R(b>>>0);T(a,{name:b,g:d=>d,l:(d,e)=>e,j:ed(b,c),m:null})}function lb(a,b,c,d,e){a>>>=0;c>>>=0;b=R(b>>>0);let f=l=>l;if(0===d){var k=32-8*c;f=l=>l<<k>>>k;e=f(e)}T(a,{name:b,g:f,l:(l,p)=>p,j:ad(b,c,0!==d),m:null})}
function mb(a,b,c){function d(f){var k=(v(),D)[f>>>2>>>0];f=(v(),D)[f+4>>>2>>>0];return new e((v(),x).buffer,f,k)}a>>>=0;var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=R(c>>>0);T(a,{name:c,g:d,j:d},{I:!0})}
var X=(a,b,c)=>{var d=(v(),y);b>>>=0;if(0<c){var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var k=a.codePointAt(f);if(127>=k){if(b>=c)break;d[b++>>>0]=k}else if(2047>=k){if(b+1>=c)break;d[b++>>>0]=192|k>>6;d[b++>>>0]=128|k&63}else if(65535>=k){if(b+2>=c)break;d[b++>>>0]=224|k>>12;d[b++>>>0]=128|k>>6&63;d[b++>>>0]=128|k&63}else{if(b+3>=c)break;d[b++>>>0]=240|k>>18;d[b++>>>0]=128|k>>12&63;d[b++>>>0]=128|k>>6&63;d[b++>>>0]=128|k&63;f++}}d[b>>>0]=0;a=b-e}else a=0;return a},fd=a=>{for(var b=0,c=0;c<a.length;++c){var d=
a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b};
function nb(a,b){a>>>=0;b=R(b>>>0);T(a,{name:b,g(c){var d=(v(),D)[c>>>2>>>0];d=Wc(c+4,d,!0);I(c);return d},l(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new S("Cannot pass non-string to std::string");var f=e?fd(d):d.length;var k=uc(4+f+1),l=k+4;(v(),D)[k>>>2>>>0]=f;e?X(d,l,f+1):(v(),y).set(d,l>>>0);null!==c&&c.push(I,k);return k},j:cd,m(c){I(c)}})}
var gd=globalThis.TextDecoder?new TextDecoder("utf-16le"):void 0,hd=(a,b,c)=>{a>>>=1;b=Uc((v(),B),a,b/2,c);if(16<b-a&&gd)return gd.decode((v(),B).slice(a,b));for(c="";a<b;++a){var d=(v(),B)[a>>>0];c+=String.fromCharCode(d)}return c},jd=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);(v(),A)[b>>>1>>>0]=f;b+=2}(v(),A)[b>>>1>>>0]=0;return b-d},kd=a=>2*a.length,ld=(a,b,c)=>{var d="";a>>>=2;for(var e=0;!(e>=b/4);e++){var f=(v(),
D)[a+e>>>0];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},md=(a,b,c)=>{b>>>=0;c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;(v(),C)[b>>>2>>>0]=f;b+=4;if(b+4>c)break}(v(),C)[b>>>2>>>0]=0;return b-d},nd=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b};
function ob(a,b,c){a>>>=0;b>>>=0;c>>>=0;c=R(c);if(2===b){var d=hd;var e=jd;var f=kd}else d=ld,e=md,f=nd;T(a,{name:c,g:k=>{var l=(v(),D)[k>>>2>>>0];l=d(k+4,l*b,!0);I(k);return l},l:(k,l)=>{if("string"!=typeof l)throw new S(`Cannot pass non-string to C++ string type ${c}`);var p=f(l),z=uc(4+p+b);(v(),D)[z>>>2>>>0]=p/b;e(l,z+4,p+b);null!==k&&k.push(I,z);return z},j:cd,m(k){I(k)}})}function pb(a,b){a>>>=0;b=R(b>>>0);T(a,{K:!0,name:b,g:()=>{},l:()=>{}})}
function qb(a){za(a>>>0,!h,1,!aa,131072,!1);Aa()}var Qc=a=>{if(!pa)try{if(a(),!(0<O))try{n?tc()&&xc(u):ic(u)}catch(b){b instanceof Fc||"unwind"==b||da(1,b)}}catch(b){b instanceof Fc||"unwind"==b||da(1,b)}},od=!Atomics.waitAsync||globalThis.navigator?.userAgent&&91>Number((navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)||[])[2]);function Ba(a){a>>>=0;od||(Atomics.waitAsync((v(),C),a>>>2,a).value.then(Ea),a+=128,Atomics.store((v(),C),a>>>2,1))}var Ea=()=>Qc(()=>{var a=tc();a&&(Ba(a),zc())});
function rb(a,b){a>>>=0;a==b>>>0?setTimeout(Ea):n?postMessage({s:a,i:"checkMailbox"}):(a=N[a])&&a.postMessage({i:"checkMailbox"})}var pd=[];function sb(a,b,c,d,e){b>>>=0;e>>>=0;pd.length=0;c=e>>>3;for(d=e+d>>>3;c<d;){var f;(v(),F)[c++>>>0]?f=(v(),F)[c++>>>0]:f=(v(),E)[c++>>>0];pd.push(f)}return(b?qd[b]:rd[a])(...pd)}var tb=()=>{O=0};function ub(a){a>>>=0;n?postMessage({i:"cleanupThread",O:a}):Pc(N[a])}function vb(a){m&&N[a>>>0].ref()}function pc(a){return(...b)=>a(...b)}
var oc=null,sd=async a=>{O+=1;try{return await a()}finally{--O}};function wb(a){a>>>=0;return sd(async()=>{var b=await V(a);return W(b)})}wb.J=!0;
var td=[],ud=a=>{var b=td.length;td.push(a);return b},vd=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=(v(),D)[b+4*d>>>2>>>0],k=Yc[f];if(void 0===k)throw a=`parameter ${d}`,f=sc(f),b=R(f),I(f),new S(`${a} has unknown type ${b}`);c[e]=k}return c},wd=(a,b,c)=>{var d=[];a=a(d,c);d.length&&((v(),D)[b>>>2>>>0]=W(d));return a},xd={},yd=a=>{var b=xd[a];return void 0===b?R(a):b};
function xb(a,b,c){var [d,...e]=vd(a,b>>>0);b=d.l.bind(d);var f=e.map(p=>p.j.bind(p));a--;var k={toValue:V};a=f.map((p,z)=>{var Q=`argFromPtr${z}`;k[Q]=p;return`${Q}(args${z?"+"+8*z:""})`});switch(c){case 0:var l="toValue(handle)";break;case 2:l="new (toValue(handle))";break;case 3:l="";break;case 1:k.getStringOrSymbol=yd,l="toValue(handle)[getStringOrSymbol(methodName)]"}l+=`(${a})`;d.K||(k.toReturnWire=b,k.emval_returnValue=wd,l=`return emval_returnValue(toReturnWire, destructorsRef, ${l})`);l=
`return function (handle, methodName, destructorsRef, args) {\n  ${l}\n  }`;c=(new Function(Object.keys(k),l))(...Object.values(k));l=`methodCaller<(${e.map(p=>p.name)}) => ${d.name}>`;return ud(Object.defineProperty(c,"name",{value:l}))}function zb(a,b){b>>>=0;a=V(a>>>0);b=V(b);return a==b}function Ab(a){a>>>=0;if(!a)return W(globalThis);a=yd(a);return W(globalThis[a])}function Bb(a){a=yd(a>>>0);return W(g[a])}function Cb(a,b){b>>>=0;a=V(a>>>0);b=V(b);return W(a[b])}
function Db(a){a>>>=0;9<a&&(U[a+1]+=1)}function Eb(a,b,c,d,e){return td[a>>>0](b>>>0,c>>>0,d>>>0,e>>>0)}function Fb(a,b,c,d,e){return Eb(a>>>0,b>>>0,c>>>0,d>>>0,e>>>0)}function Gb(){return W([])}function Hb(a){a=V(a>>>0);for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return W(b)}function Ib(a){return W(yd(a>>>0))}function Jb(){return W({})}function Kb(a){a>>>=0;for(var b=V(a);b.length;){var c=b.pop();b.pop()(c)}yb(a)}function Lb(a,b,c){b>>>=0;c>>>=0;a=V(a>>>0);b=V(b);c=V(c);a[b]=c}
function Mb(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);(v(),C)[b>>>2>>>0]=a.getUTCSeconds();(v(),C)[b+4>>>2>>>0]=a.getUTCMinutes();(v(),C)[b+8>>>2>>>0]=a.getUTCHours();(v(),C)[b+12>>>2>>>0]=a.getUTCDate();(v(),C)[b+16>>>2>>>0]=a.getUTCMonth();(v(),C)[b+20>>>2>>>0]=a.getUTCFullYear()-1900;(v(),C)[b+24>>>2>>>0]=a.getUTCDay();a=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;(v(),C)[b+28>>>2>>>0]=a}
var zd=a=>0===a%4&&(0!==a%100||0===a%400),Ad=[0,31,60,91,121,152,182,213,244,274,305,335],Bd=[0,31,59,90,120,151,181,212,243,273,304,334];
function Nb(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);(v(),C)[b>>>2>>>0]=a.getSeconds();(v(),C)[b+4>>>2>>>0]=a.getMinutes();(v(),C)[b+8>>>2>>>0]=a.getHours();(v(),C)[b+12>>>2>>>0]=a.getDate();(v(),C)[b+16>>>2>>>0]=a.getMonth();(v(),C)[b+20>>>2>>>0]=a.getFullYear()-1900;(v(),C)[b+24>>>2>>>0]=a.getDay();var c=(zd(a.getFullYear())?Ad:Bd)[a.getMonth()]+a.getDate()-1|0;(v(),C)[b+28>>>2>>>0]=c;(v(),C)[b+36>>>2>>>0]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),
6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();a=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;(v(),C)[b+32>>>2>>>0]=a}
function Ob(a){a>>>=0;var b=new Date((v(),C)[a+20>>>2>>>0]+1900,(v(),C)[a+16>>>2>>>0],(v(),C)[a+12>>>2>>>0],(v(),C)[a+8>>>2>>>0],(v(),C)[a+4>>>2>>>0],(v(),C)[a>>>2>>>0],0),c=(v(),C)[a+32>>>2>>>0],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),k=Math.min(f,e);0>c?(v(),C)[a+32>>>2>>>0]=Number(e!=f&&k==d):0<c!=(k==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?k:e)-d)));(v(),C)[a+24>>>2>>>0]=b.getDay();c=(zd(b.getFullYear())?
Ad:Bd)[b.getMonth()]+b.getDate()-1|0;(v(),C)[a+28>>>2>>>0]=c;(v(),C)[a>>>2>>>0]=b.getSeconds();(v(),C)[a+4>>>2>>>0]=b.getMinutes();(v(),C)[a+8>>>2>>>0]=b.getHours();(v(),C)[a+12>>>2>>>0]=b.getDate();(v(),C)[a+16>>>2>>>0]=b.getMonth();(v(),C)[a+20>>>2>>>0]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)}function Pb(a,b,c,d,e,f,k){return n?P(16,1,a,b,c,d,e,f,k):-52}function Qb(a,b,c,d,e,f){if(n)return P(17,1,a,b,c,d,e,f)}var Y={},ac=()=>performance.timeOrigin+performance.now();
function Rb(a,b){if(n)return P(18,1,a,b);Y[a]&&(clearTimeout(Y[a].id),delete Y[a]);if(!b)return 0;var c=setTimeout(()=>{delete Y[a];Qc(()=>yc(a,performance.timeOrigin+performance.now()))},b);Y[a]={id:c,X:b};return 0}
function Sb(a,b,c,d){a>>>=0;b>>>=0;c>>>=0;d>>>=0;var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var k=Math.max(f,e);(v(),D)[a>>>2>>>0]=60*k;(v(),C)[b>>>2>>>0]=Number(f!=e);b=l=>{var p=Math.abs(l);return`UTC${0<=l?"-":"+"}${String(Math.floor(p/60)).padStart(2,"0")}${String(p%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(X(a,c,17),X(b,d,17)):(X(a,d,17),X(b,c,17))}var Xb=()=>Date.now(),Cd=1;
function Tb(a,b,c){c>>>=0;if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(Cd)a=performance.timeOrigin+performance.now();else return 52;a=Math.round(1E6*a);(v(),F)[c>>>3>>>0]=BigInt(a);return 0}var Dd=[],Ed=(a,b)=>{Dd.length=0;for(var c;c=(v(),y)[a++>>>0];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;Dd.push(112==c?(v(),D)[b>>>2>>>0]:106==c?(v(),F)[b>>>3>>>0]:105==c?(v(),C)[b>>>2>>>0]:(v(),E)[b>>>3>>>0]);b+=d?8:4}return Dd};function Ub(a,b,c){a>>>=0;b=Ed(b>>>0,c>>>0);return qd[a](...b)}
function Vb(a,b,c){a>>>=0;b=Ed(b>>>0,c>>>0);return qd[a](...b)}var Wb=()=>{};function Yb(a,b){return q(Wc(a>>>0,b>>>0))}var Zb=()=>{O+=1;throw"unwind";};function $b(){return 4294901760}var bc=()=>m?require("os").cpus().length:navigator.hardwareConcurrency,Z={},Fd=a=>{var b;return(b=/\bwasm-function\[\d+\]:(0x[0-9a-f]+)/.exec(a))?+b[1]:(b=/:(\d+):\d+(?:\)|$)/.exec(a))?2147483648|+b[1]:0},Gd=a=>{for(var b of a)(a=Fd(b))&&(Z[a]=b)};
function ec(){var a=Error().stack.toString().split("\n");"Error"==a[0]&&a.shift();Gd(a);Z.v=Fd(a[3]);Z.L=a;return Z.v}function cc(a){a=Z[a>>>0];if(!a)return 0;var b;if(b=/^\s+at .*\.wasm\.(.*) \(.*\)$/.exec(a))a=b[1];else if(b=/^\s+at (.*) \(.*\)$/.exec(a))a=b[1];else if(b=/^(.+?)@/.exec(a))a=b[1];else return 0;I(cc.A??0);b=fd(a)+1;var c=uc(b);c&&X(a,c,b);cc.A=c;return cc.A}
function dc(a){a>>>=0;var b=(v(),y).length;if(a<=b||4294901760<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(4294901760,65536*Math.ceil(Math.max(a,d)/65536))-w.buffer.byteLength+65535)/65536|0;try{w.grow(d);qa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1}
function fc(a,b,c){a>>>=0;b>>>=0;if(Z.v==a)var d=Z.L;else d=Error().stack.toString().split("\n"),"Error"==d[0]&&d.shift(),Gd(d);for(var e=3;d[e]&&Fd(d[e])!=a;)++e;for(a=0;a<c&&d[a+e];++a)(v(),C)[b+4*a>>>2>>>0]=Fd(d[a+e]);return a}
var Hd={},Jd=()=>{if(!Id){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Hd)void 0===Hd[b]?delete a[b]:a[b]=Hd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Id=c}return Id},Id;function gc(a,b){if(n)return P(19,1,a,b);a>>>=0;b>>>=0;var c=0,d=0,e;for(e of Jd()){var f=b+c;(v(),D)[a+d>>>2>>>0]=f;c+=X(e,f,Infinity)+1;d+=4}return 0}
function hc(a,b){if(n)return P(20,1,a,b);a>>>=0;b>>>=0;var c=Jd();(v(),D)[a>>>2>>>0]=c.length;a=0;for(var d of c)a+=fd(d)+1;(v(),D)[b>>>2>>>0]=a;return 0}function jc(a){return n?P(21,1,a):52}function kc(a,b,c,d){return n?P(22,1,a,b,c,d):52}function lc(a,b,c,d){return n?P(23,1,a,b,c,d):70}var Kd=[null,[],[]];
function mc(a,b,c,d){if(n)return P(24,1,a,b,c,d);b>>>=0;c>>>=0;d>>>=0;for(var e=0,f=0;f<c;f++){var k=(v(),D)[b>>>2>>>0],l=(v(),D)[b+4>>>2>>>0];b+=8;for(var p=0;p<l;p++){var z=a,Q=(v(),y)[k+p>>>0],Va=Kd[z];0===Q||10===Q?((1===z?oa:q)(Vc(Va)),Va.length=0):Va.push(Q)}e+=l}(v(),D)[d>>>2>>>0]=e;return 0}n||Nc();n||(w=new WebAssembly.Memory({initial:256,maximum:65536,shared:!0}),qa());g.wasmBinary&&(r=g.wasmBinary);g.stackSave=()=>Dc();g.stackRestore=a=>Bc(a);g.stackAlloc=a=>Cc(a);
g.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":(v(),x)[a>>>0]=b;break;case "i8":(v(),x)[a>>>0]=b;break;case "i16":(v(),A)[a>>>1>>>0]=b;break;case "i32":(v(),C)[a>>>2>>>0]=b;break;case "i64":(v(),F)[a>>>3>>>0]=BigInt(b);break;case "float":(v(),Ga)[a>>>2>>>0]=b;break;case "double":(v(),E)[a>>>3>>>0]=b;break;case "*":(v(),D)[a>>>2>>>0]=b;break;default:Ka(`invalid type for setValue: ${c}`)}};
g.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return(v(),x)[a>>>0];case "i8":return(v(),x)[a>>>0];case "i16":return(v(),A)[a>>>1>>>0];case "i32":return(v(),C)[a>>>2>>>0];case "i64":return(v(),F)[a>>>3>>>0];case "float":return(v(),Ga)[a>>>2>>>0];case "double":return(v(),E)[a>>>3>>>0];case "*":return(v(),D)[a>>>2>>>0];default:Ka(`invalid type for getValue: ${b}`)}};g.UTF8ToString=Wc;g.stringToUTF8=X;g.lengthBytesUTF8=fd;
var rd=[nc,Mc,Sc,Ta,Ua,Wa,Xa,Ya,Za,$a,ab,bb,cb,db,eb,fb,Pb,Qb,Rb,gc,hc,jc,kc,lc,mc],qd={1055800:(a,b,c,d,e)=>{if("undefined"==typeof g||!g.o)return 1;a=Wc(Number(a>>>0));a.startsWith("./")&&(a=a.substring(2));a=g.o.get(a);if(!a)return 2;b=Number(b>>>0);c=Number(c>>>0);d=Number(d>>>0);if(b+c>a.byteLength)return 3;try{const f=a.subarray(b,b+c);switch(e){case 0:(v(),y).set(f,d>>>0);break;case 1:g.S?g.S(d,f):g.W(d,f);break;default:return 4}return 0}catch{return 4}},1056624:(a,b,c)=>{g.D(a,(v(),y).subarray(b>>>
0,b+c>>>0))},1056688:()=>g.U(),1056730:a=>{g.C(a)},1056767:()=>"undefined"!==typeof wasmOffsetConverter};function Ra(){return"undefined"!==typeof wasmOffsetConverter}var sc,Ca,tc,I,uc,za,Fa,vc,wc,xc,yc,zc,La,Ac,Bc,Cc,Dc,Ec,H;
function qc(){var a=G;a=Object.assign({},a);var b=d=>e=>d(e)>>>0,c=d=>()=>d()>>>0;a.__getTypeName=b(a.__getTypeName);a.pthread_self=c(a.pthread_self);a.malloc=b(a.malloc);a._emscripten_stack_alloc=b(a._emscripten_stack_alloc);a.emscripten_stack_get_current=c(a.emscripten_stack_get_current);return a}function xa(){0<J?K=xa:n?(ra?.(g),Ja()):(Ic(),0<J?K=xa:async function(){g.calledRun=!0;pa||(Ja(),ra?.(g))}())}var G;n||(G=await (wa()),xa());g.PTR_SIZE=4;
g.webnnInit=a=>{const b=a[0];[g.U,g.C,g.webnnEnsureTensor,g.D,g.webnnDownloadTensor,g.T,g.webnnEnableTraceEvent]=a.slice(1);g.webnnReleaseTensorId=g.C;g.webnnUploadTensor=g.D;g.webnnRegisterMLContext=g.T;g.webnnOnRunStart=c=>b.onRunStart(c);g.webnnOnRunEnd=b.onRunEnd.bind(b);g.webnnOnReleaseSession=c=>{b.onReleaseSession(c)};g.webnnCreateMLTensorDownloader=(c,d)=>b.createMLTensorDownloader(c,d);g.webnnRegisterMLTensor=(c,d,e,f)=>b.registerMLTensor(c,d,e,f);g.webnnCreateMLContext=c=>b.createMLContext(c);
g.webnnRegisterMLConstant=(c,d,e,f,k,l)=>b.registerMLConstant(c,d,e,f,k,g.o,l);g.webnnRegisterGraphInput=b.registerGraphInput.bind(b);g.webnnIsGraphInput=b.isGraphInput.bind(b);g.webnnRegisterGraphOutput=b.registerGraphOutput.bind(b);g.webnnIsGraphOutput=b.isGraphOutput.bind(b);g.webnnCreateTemporaryTensor=b.createTemporaryTensor.bind(b);g.webnnIsGraphInputOutputTypeSupported=b.isGraphInputOutputTypeSupported.bind(b)};Ia?moduleRtn=g:moduleRtn=new Promise((a,b)=>{ra=a;sa=b});
;return moduleRtn}export default ortWasmThreaded;var isPthread=globalThis.self?.name?.startsWith("em-pthread");var isNode=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";if(isNode)isPthread=(await import("worker_threads")).workerData==="em-pthread";isPthread&&ortWasmThreaded();
