
var ortWasmThreaded = (() => {
  var _scriptName = import.meta.url;
  
  return (
async function(moduleArg = {}) {
  var moduleRtn;

function d(){k.buffer!=m.buffer&&p();return m}function t(){k.buffer!=m.buffer&&p();return aa}function x(){k.buffer!=m.buffer&&p();return ba}function y(){k.buffer!=m.buffer&&p();return ca}function da(){k.buffer!=m.buffer&&p();return ea}var z=moduleArg,fa,A,ha=new Promise((a,b)=>{fa=a;A=b}),ia="object"==typeof window,B="function"==typeof importScripts,C="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,D=B&&"em-pthread"==self.name;
if(C){const {createRequire:a}=await import("module");var require=a(import.meta.url),ja=require("worker_threads");global.Worker=ja.Worker;D=(B=!ja.wb)&&"em-pthread"==ja.workerData}"use strict";z.mountExternalData=(a,b)=>{a.startsWith("./")&&(a=a.substring(2));(z.Za||(z.Za=new Map)).set(a,b)};z.unmountExternalData=()=>{delete z.Za};var SharedArrayBuffer=globalThis.SharedArrayBuffer??(new WebAssembly.Memory({initial:0,maximum:0,shared:!0})).buffer.constructor;"use strict";
let la=()=>{const a=(c,e,f)=>(...g)=>{const h=E,l=e?.();g=c(...g);const n=e?.();l!==n&&(c=n,f(l),e=f=null);return E!=h?ka():g},b=c=>async(...e)=>{try{if(z.Ya)throw Error("Session already started");const f=z.Ya={rb:e[0],errors:[]},g=await c(...e);if(z.Ya!==f)throw Error("Session mismatch");z.cb?.flush();const h=f.errors;if(0<h.length){let l=await Promise.all(h);l=l.filter(n=>n);if(0<l.length)throw Error(l.join("\n"));}return g}finally{z.Ya=null}};z._OrtCreateSession=a(z._OrtCreateSession,()=>z._OrtCreateSession,
c=>z._OrtCreateSession=c);z._OrtRun=b(a(z._OrtRun,()=>z._OrtRun,c=>z._OrtRun=c));z._OrtRunWithBinding=b(a(z._OrtRunWithBinding,()=>z._OrtRunWithBinding,c=>z._OrtRunWithBinding=c));z._OrtBindInput=a(z._OrtBindInput,()=>z._OrtBindInput,c=>z._OrtBindInput=c);la=void 0};
z.jsepInit=(a,b)=>{la?.();if("webgpu"===a){[z.cb,z.ib,z.mb,z.eb,z.lb,z.Ha,z.nb,z.pb,z.jb,z.kb,z.ob]=b;const c=z.cb;z.jsepRegisterBuffer=(e,f,g,h)=>c.registerBuffer(e,f,g,h);z.jsepGetBuffer=e=>c.getBuffer(e);z.jsepCreateDownloader=(e,f,g)=>c.createDownloader(e,f,g);z.jsepOnReleaseSession=e=>{c.onReleaseSession(e)};z.jsepOnRunStart=e=>c.onRunStart(e)}};var ma=Object.assign({},z),na="./this.program",oa=(a,b)=>{throw b;},F="",pa,qa;
if(C){var fs=require("fs"),ra=require("path");F=require("url").fileURLToPath(new URL("./",import.meta.url));qa=a=>{a=sa(a)?new URL(a):ra.normalize(a);return fs.readFileSync(a)};pa=a=>{a=sa(a)?new URL(a):ra.normalize(a);return new Promise((b,c)=>{fs.readFile(a,void 0,(e,f)=>{e?c(e):b(f.buffer)})})};!z.thisProgram&&1<process.argv.length&&(na=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);oa=(a,b)=>{process.exitCode=a;throw b;}}else if(ia||B)B?F=self.location.href:"undefined"!=
typeof document&&document.currentScript&&(F=document.currentScript.src),_scriptName&&(F=_scriptName),F.startsWith("blob:")?F="":F=F.substr(0,F.replace(/[?#].*/,"").lastIndexOf("/")+1),C||(B&&(qa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),pa=a=>sa(a)?new Promise((b,c)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{(200==e.status||0==e.status&&e.response)&&c(e.response);b(e.status)};
e.onerror=b;e.send(null)}):fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url))));C&&"undefined"==typeof performance&&(global.performance=require("perf_hooks").performance);var ta=console.log.bind(console),ua=console.error.bind(console);C&&(ta=(...a)=>fs.writeSync(1,a.join(" ")+"\n"),ua=(...a)=>fs.writeSync(2,a.join(" ")+"\n"));var va=ta,H=ua;Object.assign(z,ma);ma=null;
if(D){var wa;if(C){var xa=ja.parentPort;xa.on("message",b=>onmessage({data:b}));Object.assign(globalThis,{self:global,importScripts:()=>{},postMessage:b=>xa.postMessage(b),performance:global.performance||{now:Date.now}})}var ya=!1;H=function(...b){b=b.join(" ");C?fs.writeSync(2,b+"\n"):console.error(b)};self.alert=function(...b){postMessage({bb:"alert",text:b.join(" "),xb:I()})};z.instantiateWasm=(b,c)=>new Promise(e=>{wa=f=>{f=new WebAssembly.Instance(f,za());c(f);e()}});self.onunhandledrejection=
b=>{throw b.reason||b;};function a(b){try{var c=b.data,e=c.cmd;if("load"===e){let f=[];self.onmessage=g=>f.push(g);self.startWorker=()=>{postMessage({cmd:"loaded"});for(let g of f)a(g);self.onmessage=a};for(const g of c.handlers)if(!z[g]||z[g].proxy)z[g]=(...h)=>{postMessage({bb:"callHandler",vb:g,args:h})},"print"==g&&(va=z[g]),"printErr"==g&&(H=z[g]);k=c.wasmMemory;p();wa(c.wasmModule)}else if("run"===e){Aa(c.pthread_ptr,0,0,1,0,0);Ba(c.pthread_ptr);Ca();Da();ya||=!0;try{Ea(c.start_routine,c.arg)}catch(f){if("unwind"!=
f)throw f;}}else"cancel"===e?I()&&Fa(-1):"setimmediate"!==c.target&&("checkMailbox"===e?ya&&Ga():e&&(H(`worker: received unknown command ${e}`),H(c)))}catch(f){throw Ha(),f;}}self.onmessage=a}var J;z.wasmBinary&&(J=z.wasmBinary);var k,Ia,K=!1,L,m,aa,ba,ca,Ja,M,ea;
function p(){var a=k.buffer;z.HEAP8=m=new Int8Array(a);z.HEAP16=new Int16Array(a);z.HEAPU8=aa=new Uint8Array(a);z.HEAPU16=new Uint16Array(a);z.HEAP32=ba=new Int32Array(a);z.HEAPU32=ca=new Uint32Array(a);z.HEAPF32=Ja=new Float32Array(a);z.HEAPF64=ea=new Float64Array(a);z.HEAP64=M=new BigInt64Array(a);z.HEAPU64=new BigUint64Array(a)}
if(!D){k=new WebAssembly.Memory({initial:256,maximum:65536,shared:!0});if(!(k.buffer instanceof SharedArrayBuffer))throw H("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),C&&H("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and/or recent version)"),Error("bad memory");p()}
var Ka=[],La=[],Ma=[],N=0,Na=null,O=null;function Oa(){N--;if(0==N&&(null!==Na&&(clearInterval(Na),Na=null),O)){var a=O;O=null;a()}}function P(a){a="Aborted("+a+")";H(a);K=!0;L=1;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");A(a);throw a;}var Pa=a=>a.startsWith("data:application/octet-stream;base64,"),sa=a=>a.startsWith("file://"),Qa;function Ra(a){if(a==Qa&&J)return new Uint8Array(J);if(qa)return qa(a);throw"both async and sync fetching of the wasm failed";}
function Sa(a){return J?Promise.resolve().then(()=>Ra(a)):pa(a).then(b=>new Uint8Array(b),()=>Ra(a))}function Ta(a,b,c){return Sa(a).then(e=>WebAssembly.instantiate(e,b)).then(c,e=>{H(`failed to asynchronously prepare wasm: ${e}`);P(e)})}
function Ua(a,b){var c=Qa;return J||"function"!=typeof WebAssembly.instantiateStreaming||Pa(c)||sa(c)||C||"function"!=typeof fetch?Ta(c,a,b):fetch(c,{credentials:"same-origin"}).then(e=>WebAssembly.instantiateStreaming(e,a).then(b,function(f){H(`wasm streaming compile failed: ${f}`);H("falling back to ArrayBuffer instantiation");return Ta(c,a,b)}))}
function za(){Va={j:Wa,D:Xa,b:Ya,C:Za,g:$a,T:ab,y:bb,A:cb,U:db,R:eb,K:fb,Q:gb,p:hb,z:ib,w:jb,S:kb,x:lb,Y:mb,X:nb,N:ob,u:pb,E:qb,k:rb,M:Ba,W:sb,H:tb,I:ub,J:vb,F:wb,G:xb,_:yb,c:zb,m:Ab,l:Bb,q:Cb,e:Db,V:Fb,v:Gb,d:Hb,f:Ib,i:Jb,t:Kb,s:Lb,r:Mb,O:Nb,P:Ob,B:Pb,h:Qb,o:Rb,L:Sb,n:Tb,a:k,Z:Ub};return{a:Va}}
var Vb={782940:(a,b,c,e)=>{if("undefined"==typeof z||!z.Za)return 1;a=Q(a>>>0);a.startsWith("./")&&(a=a.substring(2));a=z.Za.get(a);if(!a)return 2;b>>>=0;c>>>=0;e>>>=0;if(b+c>a.byteLength)return 3;try{return t().set(a.subarray(b,b+c),e>>>0),0}catch{return 4}},783441:()=>{z.jb()},783472:()=>{z.kb()},783501:()=>{z.ob()},783526:a=>z.ib(a),783559:a=>z.mb(a),783591:(a,b,c)=>{z.eb(a,b,c,!0)},783630:(a,b,c)=>{z.eb(a,b,c)},783663:()=>"undefined"!==typeof wasmOffsetConverter,783720:a=>{z.Ha("Abs",a,void 0)},
783771:a=>{z.Ha("Neg",a,void 0)},783822:a=>{z.Ha("Floor",a,void 0)},783875:a=>{z.Ha("Ceil",a,void 0)},783927:a=>{z.Ha("Reciprocal",a,void 0)},783985:a=>{z.Ha("Sqrt",a,void 0)},784037:a=>{z.Ha("Exp",a,void 0)},784088:a=>{z.Ha("Erf",a,void 0)},784139:a=>{z.Ha("Sigmoid",a,void 0)},784194:(a,b,c)=>{z.Ha("HardSigmoid",a,{alpha:b,beta:c})},784273:a=>{z.Ha("Log",a,void 0)},784324:a=>{z.Ha("Sin",a,void 0)},784375:a=>{z.Ha("Cos",a,void 0)},784426:a=>{z.Ha("Tan",a,void 0)},784477:a=>{z.Ha("Asin",a,void 0)},
784529:a=>{z.Ha("Acos",a,void 0)},784581:a=>{z.Ha("Atan",a,void 0)},784633:a=>{z.Ha("Sinh",a,void 0)},784685:a=>{z.Ha("Cosh",a,void 0)},784737:a=>{z.Ha("Asinh",a,void 0)},784790:a=>{z.Ha("Acosh",a,void 0)},784843:a=>{z.Ha("Atanh",a,void 0)},784896:a=>{z.Ha("Tanh",a,void 0)},784948:a=>{z.Ha("Not",a,void 0)},784999:(a,b,c)=>{z.Ha("Clip",a,{min:b,max:c})},785068:a=>{z.Ha("Clip",a,void 0)},785120:(a,b)=>{z.Ha("Elu",a,{alpha:b})},785178:a=>{z.Ha("Gelu",a,void 0)},785230:a=>{z.Ha("Relu",a,void 0)},785282:(a,
b)=>{z.Ha("LeakyRelu",a,{alpha:b})},785346:(a,b)=>{z.Ha("ThresholdedRelu",a,{alpha:b})},785416:(a,b)=>{z.Ha("Cast",a,{to:b})},785474:a=>{z.Ha("Add",a,void 0)},785525:a=>{z.Ha("Sub",a,void 0)},785576:a=>{z.Ha("Mul",a,void 0)},785627:a=>{z.Ha("Div",a,void 0)},785678:a=>{z.Ha("Pow",a,void 0)},785729:a=>{z.Ha("Equal",a,void 0)},785782:a=>{z.Ha("Greater",a,void 0)},785837:a=>{z.Ha("GreaterOrEqual",a,void 0)},785899:a=>{z.Ha("Less",a,void 0)},785951:a=>{z.Ha("LessOrEqual",a,void 0)},786010:(a,b,c,e,f)=>
{z.Ha("ReduceMean",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:e?Array.from(x().subarray(e>>>0,f>>>0)):[]})},786169:(a,b,c,e,f)=>{z.Ha("ReduceMax",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:e?Array.from(x().subarray(e>>>0,f>>>0)):[]})},786327:(a,b,c,e,f)=>{z.Ha("ReduceMin",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:e?Array.from(x().subarray(e>>>0,f>>>0)):[]})},786485:(a,b,c,e,f)=>{z.Ha("ReduceProd",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:e?Array.from(x().subarray(e>>>0,f>>>0)):[]})},786644:(a,b,
c,e,f)=>{z.Ha("ReduceSum",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:e?Array.from(x().subarray(e>>>0,f>>>0)):[]})},786802:(a,b,c,e,f)=>{z.Ha("ReduceL1",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:e?Array.from(x().subarray(e>>>0,f>>>0)):[]})},786959:(a,b,c,e,f)=>{z.Ha("ReduceL2",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:e?Array.from(x().subarray(e>>>0,f>>>0)):[]})},787116:(a,b,c,e,f)=>{z.Ha("ReduceLogSum",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:e?Array.from(x().subarray(e>>>0,f>>>0)):[]})},787277:(a,
b,c,e,f)=>{z.Ha("ReduceSumSquare",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:e?Array.from(x().subarray(e>>>0,f>>>0)):[]})},787441:(a,b,c,e,f)=>{z.Ha("ReduceLogSumExp",a,{keepDims:!!b,noopWithEmptyAxes:!!c,axes:e?Array.from(x().subarray(e>>>0,f>>>0)):[]})},787605:a=>{z.Ha("Where",a,void 0)},787658:(a,b,c)=>{z.Ha("Transpose",a,{perm:b?Array.from(x().subarray(b>>>0,c>>>0)):[]})},787766:(a,b,c,e)=>{z.Ha("DepthToSpace",a,{blocksize:b,mode:Q(c),format:e?"NHWC":"NCHW"})},787899:(a,b,c,e)=>{z.Ha("DepthToSpace",
a,{blocksize:b,mode:Q(c),format:e?"NHWC":"NCHW"})},788032:(a,b,c,e,f,g,h,l,n,q,r,u,v,w,G)=>{z.Ha("ConvTranspose",a,{format:n?"NHWC":"NCHW",autoPad:b,dilations:[c],group:e,kernelShape:[f],pads:[g,h],strides:[l],wIsConst:()=>!!d()[q>>>0],outputPadding:r?Array.from(x().subarray(r>>>0,u>>>0)):[],outputShape:v?Array.from(x().subarray(v>>>0,w>>>0)):[],activation:Q(G)})},788433:(a,b,c,e,f,g,h,l,n,q,r,u,v,w)=>{z.Ha("ConvTranspose",a,{format:l?"NHWC":"NCHW",autoPad:b,dilations:Array.from(x().subarray(c>>>
0,(c>>>0)+2>>>0)),group:e,kernelShape:Array.from(x().subarray(f>>>0,(f>>>0)+2>>>0)),pads:Array.from(x().subarray(g>>>0,(g>>>0)+4>>>0)),strides:Array.from(x().subarray(h>>>0,(h>>>0)+2>>>0)),wIsConst:()=>!!d()[n>>>0],outputPadding:q?Array.from(x().subarray(q>>>0,r>>>0)):[],outputShape:u?Array.from(x().subarray(u>>>0,v>>>0)):[],activation:Q(w)})},788998:(a,b,c,e,f,g,h,l,n,q,r,u,v,w,G)=>{z.Ha("ConvTranspose",a,{format:n?"NHWC":"NCHW",autoPad:b,dilations:[c],group:e,kernelShape:[f],pads:[g,h],strides:[l],
wIsConst:()=>!!d()[q>>>0],outputPadding:r?Array.from(x().subarray(r>>>0,u>>>0)):[],outputShape:v?Array.from(x().subarray(v>>>0,w>>>0)):[],activation:Q(G)})},789399:(a,b,c,e,f,g,h,l,n,q,r,u,v,w)=>{z.Ha("ConvTranspose",a,{format:l?"NHWC":"NCHW",autoPad:b,dilations:Array.from(x().subarray(c>>>0,(c>>>0)+2>>>0)),group:e,kernelShape:Array.from(x().subarray(f>>>0,(f>>>0)+2>>>0)),pads:Array.from(x().subarray(g>>>0,(g>>>0)+4>>>0)),strides:Array.from(x().subarray(h>>>0,(h>>>0)+2>>>0)),wIsConst:()=>!!d()[n>>>
0],outputPadding:q?Array.from(x().subarray(q>>>0,r>>>0)):[],outputShape:u?Array.from(x().subarray(u>>>0,v>>>0)):[],activation:Q(w)})},789964:(a,b)=>{z.Ha("GlobalAveragePool",a,{format:b?"NHWC":"NCHW"})},790055:(a,b,c,e,f,g,h,l,n,q,r,u,v,w)=>{z.Ha("AveragePool",a,{format:w?"NHWC":"NCHW",auto_pad:b,ceil_mode:c,count_include_pad:e,storage_order:f,dilations:g?Array.from(x().subarray(g>>>0,h>>>0)):[],kernel_shape:l?Array.from(x().subarray(l>>>0,n>>>0)):[],pads:q?Array.from(x().subarray(q>>>0,r>>>0)):[],
strides:u?Array.from(x().subarray(u>>>0,v>>>0)):[]})},790470:(a,b)=>{z.Ha("GlobalAveragePool",a,{format:b?"NHWC":"NCHW"})},790561:(a,b,c,e,f,g,h,l,n,q,r,u,v,w)=>{z.Ha("AveragePool",a,{format:w?"NHWC":"NCHW",auto_pad:b,ceil_mode:c,count_include_pad:e,storage_order:f,dilations:g?Array.from(x().subarray(g>>>0,h>>>0)):[],kernel_shape:l?Array.from(x().subarray(l>>>0,n>>>0)):[],pads:q?Array.from(x().subarray(q>>>0,r>>>0)):[],strides:u?Array.from(x().subarray(u>>>0,v>>>0)):[]})},790976:(a,b)=>{z.Ha("GlobalMaxPool",
a,{format:b?"NHWC":"NCHW"})},791063:(a,b,c,e,f,g,h,l,n,q,r,u,v,w)=>{z.Ha("MaxPool",a,{format:w?"NHWC":"NCHW",auto_pad:b,ceil_mode:c,count_include_pad:e,storage_order:f,dilations:g?Array.from(x().subarray(g>>>0,h>>>0)):[],kernel_shape:l?Array.from(x().subarray(l>>>0,n>>>0)):[],pads:q?Array.from(x().subarray(q>>>0,r>>>0)):[],strides:u?Array.from(x().subarray(u>>>0,v>>>0)):[]})},791474:(a,b)=>{z.Ha("GlobalMaxPool",a,{format:b?"NHWC":"NCHW"})},791561:(a,b,c,e,f,g,h,l,n,q,r,u,v,w)=>{z.Ha("MaxPool",a,{format:w?
"NHWC":"NCHW",auto_pad:b,ceil_mode:c,count_include_pad:e,storage_order:f,dilations:g?Array.from(x().subarray(g>>>0,h>>>0)):[],kernel_shape:l?Array.from(x().subarray(l>>>0,n>>>0)):[],pads:q?Array.from(x().subarray(q>>>0,r>>>0)):[],strides:u?Array.from(x().subarray(u>>>0,v>>>0)):[]})},791972:(a,b,c,e,f)=>{z.Ha("Gemm",a,{alpha:b,beta:c,transA:e,transB:f})},792076:a=>{z.Ha("MatMul",a,void 0)},792130:(a,b,c,e)=>{z.Ha("ArgMax",a,{keepDims:!!b,selectLastIndex:!!c,axis:e})},792238:(a,b,c,e)=>{z.Ha("ArgMin",
a,{keepDims:!!b,selectLastIndex:!!c,axis:e})},792346:(a,b)=>{z.Ha("Softmax",a,{axis:b})},792409:(a,b)=>{z.Ha("Concat",a,{axis:b})},792469:(a,b,c,e,f)=>{z.Ha("Split",a,{axis:b,numOutputs:c,splitSizes:e?Array.from(x().subarray(e>>>0,f>>>0)):[]})},792609:a=>{z.Ha("Expand",a,void 0)},792663:(a,b)=>{z.Ha("Gather",a,{axis:Number(b)})},792734:(a,b)=>{z.Ha("GatherElements",a,{axis:Number(b)})},792813:(a,b,c,e,f,g,h,l,n,q,r)=>{z.Ha("Resize",a,{antialias:b,axes:c?Array.from(x().subarray(c>>>0,e>>>0)):[],coordinateTransformMode:Q(f),
cubicCoeffA:g,excludeOutside:h,extrapolationValue:l,keepAspectRatioPolicy:Q(n),mode:Q(q),nearestMode:Q(r)})},793159:(a,b,c,e,f,g,h)=>{z.Ha("Slice",a,{starts:b?Array.from(x().subarray(b>>>0,c>>>0)):[],ends:e?Array.from(x().subarray(e>>>0,f>>>0)):[],axes:g?Array.from(x().subarray(g>>>0,h>>>0)):[]})},793375:a=>{z.Ha("Tile",a,void 0)},793427:(a,b,c)=>{z.Ha("InstanceNormalization",a,{epsilon:b,format:c?"NHWC":"NCHW"})},793541:(a,b,c)=>{z.Ha("InstanceNormalization",a,{epsilon:b,format:c?"NHWC":"NCHW"})},
793655:a=>{z.Ha("Range",a,void 0)},793708:(a,b)=>{z.Ha("Einsum",a,{equation:Q(b)})},793789:(a,b,c,e,f)=>{z.Ha("Pad",a,{mode:b,value:c,pads:e?Array.from(x().subarray(e>>>0,f>>>0)):[]})},793916:(a,b,c,e,f,g)=>{z.Ha("BatchNormalization",a,{epsilon:b,momentum:c,spatial:!!f,trainingMode:!!e,format:g?"NHWC":"NCHW"})},794085:(a,b,c,e,f,g)=>{z.Ha("BatchNormalization",a,{epsilon:b,momentum:c,spatial:!!f,trainingMode:!!e,format:g?"NHWC":"NCHW"})},794254:(a,b,c)=>{z.Ha("CumSum",a,{exclusive:Number(b),reverse:Number(c)})},
794351:(a,b,c)=>{z.Ha("DequantizeLinear",a,{axis:b,blockSize:c})},794441:(a,b,c,e,f,g,h,l,n)=>{z.Ha("Attention",a,{numHeads:b,isUnidirectional:c,maskFilterValue:e,scale:f,doRotary:g,qkvHiddenSizes:h?Array.from(x().subarray(Number(l)>>>0,Number(l)+h>>>0)):[],pastPresentShareBuffer:!!n})},794713:a=>{z.Ha("BiasAdd",a,void 0)},794768:a=>{z.Ha("BiasSplitGelu",a,void 0)},794829:a=>{z.Ha("FastGelu",a,void 0)},794885:(a,b,c,e,f,g,h,l,n,q,r,u,v,w,G,Qc)=>{var Eb=z,Rc=Eb.Ha;c=c?Array.from(x().subarray(c>>>0,
e>>>0)):[];g=g?Array.from(x().subarray(g>>>0,h>>>0)):[];l=l?Array.from(x().subarray(l>>>0,n>>>0)):[];q=q?Array.from(x().subarray(q>>>0,r>>>0)):[];w=Q(w);G?(r=Array,n=r.from,k.buffer!=m.buffer&&p(),G=n.call(r,Ja.subarray(G>>>0,Qc>>>0))):G=[];Rc.call(Eb,"Conv",a,{format:u?"NHWC":"NCHW",auto_pad:b,dilations:c,group:f,kernel_shape:g,pads:l,strides:q,w_is_const:()=>!!d()[v>>>0],activation:w,activation_params:G})},795381:a=>{z.Ha("Gelu",a,void 0)},795433:(a,b,c,e)=>{z.Ha("GroupQueryAttention",a,{numHeads:b,
kvNumHeads:c,scale:e})},795546:(a,b,c,e)=>{z.Ha("LayerNormalization",a,{axis:b,epsilon:c,simplified:!!e})},795657:(a,b,c,e)=>{z.Ha("LayerNormalization",a,{axis:b,epsilon:c,simplified:!!e})},795768:(a,b,c,e,f,g)=>{z.Ha("MatMulNBits",a,{k:b,n:c,accuracyLevel:e,bits:f,blockSize:g})},795895:(a,b,c,e,f,g)=>{z.Ha("MultiHeadAttention",a,{numHeads:b,isUnidirectional:c,maskFilterValue:e,scale:f,doRotary:g})},796054:(a,b)=>{z.Ha("QuickGelu",a,{alpha:b})},796118:(a,b,c,e,f)=>{z.Ha("RotaryEmbedding",a,{interleaved:!!b,
numHeads:c,rotaryEmbeddingDim:e,scale:f})},796257:(a,b,c)=>{z.Ha("SkipLayerNormalization",a,{epsilon:b,simplified:!!c})},796359:a=>{z.nb(a)},796393:(a,b)=>z.pb(a,b,z.Ya.rb,z.Ya.errors),796505:(a,b,c)=>{z.Ha("SkipLayerNormalization",a,{epsilon:b,simplified:!!c})}};function Xa(a,b,c){return Wb(async()=>{await z.lb(a,b,c)})}function Wa(){return"undefined"!==typeof wasmOffsetConverter}function Xb(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Yb=a=>{a.terminate();a.onmessage=()=>{}},ac=a=>{0==R.length&&(Zb(),$b(R[0]));var b=R.pop();if(!b)return 6;S.push(b);T[a.Sa]=b;b.Sa=a.Sa;var c={cmd:"run",start_routine:a.sb,arg:a.gb,pthread_ptr:a.Sa};C&&b.unref();b.postMessage(c,a.tb);return 0},U=0,V=(a,b,...c)=>{for(var e=2*c.length,f=bc(),g=cc(8*e),h=g>>>3,l=0;l<c.length;l++){var n=c[l];"bigint"==typeof n?(M[h+2*l]=1n,M[h+2*l+1]=n):(M[h+2*l]=0n,da()[h+2*l+1>>>0]=n)}a=dc(a,0,e,g,b);ec(f);return a};
function Ub(a){if(D)return V(0,1,a);L=a;if(!(0<U)){for(var b of S)Yb(b);for(b of R)Yb(b);R=[];S=[];T=[];K=!0}oa(a,new Xb(a))}function fc(a){if(D)return V(1,0,a);Pb(a)}var Pb=a=>{L=a;if(D)throw fc(a),"unwind";Ub(a)},R=[],S=[],gc=[],T={};function hc(){for(var a=z.numThreads-1;a--;)Zb();Ka.unshift(()=>{N++;ic(()=>Oa())})}var kc=a=>{var b=a.Sa;delete T[b];R.push(a);S.splice(S.indexOf(a),1);a.Sa=0;jc(b)};function Da(){gc.forEach(a=>a())}
var $b=a=>new Promise(b=>{a.onmessage=g=>{g=g.data;var h=g.cmd;if(g.targetThread&&g.targetThread!=I()){var l=T[g.targetThread];l?l.postMessage(g,g.transferList):H(`Internal error! Worker sent a message "${h}" to target pthread ${g.targetThread}, but that thread no longer exists!`)}else if("checkMailbox"===h)Ga();else if("spawnThread"===h)ac(g);else if("cleanupThread"===h)kc(T[g.thread]);else if("killThread"===h)g=g.thread,h=T[g],delete T[g],Yb(h),jc(g),S.splice(S.indexOf(h),1),h.Sa=0;else if("cancelThread"===
h)T[g.thread].postMessage({cmd:"cancel"});else if("loaded"===h)a.loaded=!0,C&&!a.Sa&&a.unref(),b(a);else if("alert"===h)alert(`Thread ${g.threadId}: ${g.text}`);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===h)z[g.handler](...g.args);else h&&H(`worker sent an unknown command ${h}`)};a.onerror=g=>{H(`${"worker sent an error!"} ${g.filename}:${g.lineno}: ${g.message}`);throw g;};C&&(a.on("message",g=>a.onmessage({data:g})),a.on("error",g=>a.onerror(g)));var c=[],e=[],f;for(f of e)z.propertyIsEnumerable(f)&&
c.push(f);a.postMessage({cmd:"load",handlers:c,wasmMemory:k,wasmModule:Ia})});function ic(a){D?a():Promise.all(R.map($b)).then(a)}function Zb(){var a=new Worker(new URL(import.meta.url),{type:"module",workerData:"em-pthread",name:"em-pthread"});R.push(a)}var lc=a=>{for(;0<a.length;)a.shift()(z)},Ca=()=>{var a=I(),b=y()[a+52>>>2>>>0];a=y()[a+56>>>2>>>0];mc(b,b-a);ec(b)},Ea=(a,b)=>{U=0;a=nc(a,b);0<U?L=a:Fa(a)};class oc{constructor(a){this.$a=a-24}}var pc=0,qc=0;
function Ya(a,b,c){a>>>=0;var e=new oc(a);b>>>=0;c>>>=0;y()[e.$a+16>>>2>>>0]=0;y()[e.$a+4>>>2>>>0]=b;y()[e.$a+8>>>2>>>0]=c;pc=a;qc++;throw pc;}function rc(a,b,c,e){return D?V(2,1,a,b,c,e):Za(a,b,c,e)}
function Za(a,b,c,e){a>>>=0;b>>>=0;c>>>=0;e>>>=0;if("undefined"==typeof SharedArrayBuffer)return H("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;var f=[];if(D&&0===f.length)return rc(a,b,c,e);a={sb:c,Sa:a,gb:e,tb:f};return D?(a.bb="spawnThread",postMessage(a,f),0):ac(a)}
var sc="undefined"!=typeof TextDecoder?new TextDecoder:void 0,tc=(a,b,c)=>{b>>>=0;var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.buffer&&sc)return sc.decode(a.buffer instanceof SharedArrayBuffer?a.slice(b,c):a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|
f&1023))}}else e+=String.fromCharCode(f)}return e},Q=(a,b)=>(a>>>=0)?tc(t(),a,b):"";function $a(a,b,c){return D?V(3,1,a,b,c):0}function ab(a,b){if(D)return V(4,1,a,b)}
var W=(a,b,c)=>{var e=t();b>>>=0;if(0<c){var f=b;c=b+c-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(b>=c)break;e[b++>>>0]=h}else{if(2047>=h){if(b+1>=c)break;e[b++>>>0]=192|h>>6}else{if(65535>=h){if(b+2>=c)break;e[b++>>>0]=224|h>>12}else{if(b+3>=c)break;e[b++>>>0]=240|h>>18;e[b++>>>0]=128|h>>12&63}e[b++>>>0]=128|h>>6&63}e[b++>>>0]=128|h&63}}e[b>>>0]=0;a=b-f}else a=0;return a};
function bb(a,b){if(D)return V(5,1,a,b)}function cb(a,b,c){if(D)return V(6,1,a,b,c)}function db(a,b,c){return D?V(7,1,a,b,c):0}function eb(a,b){if(D)return V(8,1,a,b)}function fb(a,b,c){if(D)return V(9,1,a,b,c)}function gb(a,b,c,e){if(D)return V(10,1,a,b,c,e)}function hb(a,b,c,e){if(D)return V(11,1,a,b,c,e)}function ib(a,b,c,e){if(D)return V(12,1,a,b,c,e)}function jb(a){if(D)return V(13,1,a)}function kb(a,b){if(D)return V(14,1,a,b)}function lb(a,b,c){if(D)return V(15,1,a,b,c)}
var mb=()=>{P("")},nb=()=>1;function ob(a){Aa(a>>>0,!B,1,!ia,131072,!1);Da()}var uc=a=>{if(!K)try{if(a(),!(0<U))try{D?Fa(L):Pb(L)}catch(b){b instanceof Xb||"unwind"==b||oa(1,b)}}catch(b){b instanceof Xb||"unwind"==b||oa(1,b)}};function Ba(a){a>>>=0;"function"===typeof Atomics.ub&&(Atomics.ub(x(),a>>>2,a).value.then(Ga),a+=128,Atomics.store(x(),a>>>2,1))}var Ga=()=>{var a=I();a&&(Ba(a),uc(vc))};
function pb(a,b){a>>>=0;a==b>>>0?setTimeout(Ga):D?postMessage({targetThread:a,cmd:"checkMailbox"}):(a=T[a])&&a.postMessage({cmd:"checkMailbox"})}var wc=[];function qb(a,b,c,e,f){b>>>=0;e/=2;wc.length=e;c=f>>>0>>>3;for(f=0;f<e;f++)wc[f]=M[c+2*f]?M[c+2*f+1]:da()[c+2*f+1>>>0];return(b?Vb[b]:xc[a])(...wc)}function rb(a){a>>>=0;D?postMessage({cmd:"cleanupThread",thread:a}):kc(T[a])}function sb(a){C&&T[a>>>0].ref()}
function tb(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);x()[b>>>2>>>0]=a.getUTCSeconds();x()[b+4>>>2>>>0]=a.getUTCMinutes();x()[b+8>>>2>>>0]=a.getUTCHours();x()[b+12>>>2>>>0]=a.getUTCDate();x()[b+16>>>2>>>0]=a.getUTCMonth();x()[b+20>>>2>>>0]=a.getUTCFullYear()-1900;x()[b+24>>>2>>>0]=a.getUTCDay();a=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;x()[b+28>>>2>>>0]=a}
var yc=a=>0===a%4&&(0!==a%100||0===a%400),zc=[0,31,60,91,121,152,182,213,244,274,305,335],Ac=[0,31,59,90,120,151,181,212,243,273,304,334];
function ub(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);b>>>=0;a=new Date(1E3*a);x()[b>>>2>>>0]=a.getSeconds();x()[b+4>>>2>>>0]=a.getMinutes();x()[b+8>>>2>>>0]=a.getHours();x()[b+12>>>2>>>0]=a.getDate();x()[b+16>>>2>>>0]=a.getMonth();x()[b+20>>>2>>>0]=a.getFullYear()-1900;x()[b+24>>>2>>>0]=a.getDay();var c=(yc(a.getFullYear())?zc:Ac)[a.getMonth()]+a.getDate()-1|0;x()[b+28>>>2>>>0]=c;x()[b+36>>>2>>>0]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();
var e=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();a=(c!=e&&a.getTimezoneOffset()==Math.min(e,c))|0;x()[b+32>>>2>>>0]=a}
function vb(a){a>>>=0;var b=new Date(x()[a+20>>>2>>>0]+1900,x()[a+16>>>2>>>0],x()[a+12>>>2>>>0],x()[a+8>>>2>>>0],x()[a+4>>>2>>>0],x()[a>>>2>>>0],0),c=x()[a+32>>>2>>>0],e=b.getTimezoneOffset(),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),g=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),h=Math.min(g,f);0>c?x()[a+32>>>2>>>0]=Number(f!=g&&h==e):0<c!=(h==e)&&(f=Math.max(g,f),b.setTime(b.getTime()+6E4*((0<c?h:f)-e)));x()[a+24>>>2>>>0]=b.getDay();c=(yc(b.getFullYear())?zc:Ac)[b.getMonth()]+
b.getDate()-1|0;x()[a+28>>>2>>>0]=c;x()[a>>>2>>>0]=b.getSeconds();x()[a+4>>>2>>>0]=b.getMinutes();x()[a+8>>>2>>>0]=b.getHours();x()[a+12>>>2>>>0]=b.getDate();x()[a+16>>>2>>>0]=b.getMonth();x()[a+20>>>2>>>0]=b.getYear();a=b.getTime();return BigInt(isNaN(a)?-1:a/1E3)}function wb(a,b,c,e,f,g,h){return D?V(16,1,a,b,c,e,f,g,h):-52}function xb(a,b,c,e,f,g){if(D)return V(17,1,a,b,c,e,f,g)}
function yb(a,b,c,e){a>>>=0;b>>>=0;c>>>=0;e>>>=0;var f=(new Date).getFullYear(),g=new Date(f,0,1),h=new Date(f,6,1);f=g.getTimezoneOffset();var l=h.getTimezoneOffset(),n=Math.max(f,l);y()[a>>>2>>>0]=60*n;x()[b>>>2>>>0]=Number(f!=l);a=q=>q.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];g=a(g);h=a(h);l<f?(W(g,c,17),W(h,e,17)):(W(g,e,17),W(h,c,17))}
var Bc=[],Cc=(a,b)=>{Bc.length=0;for(var c;c=t()[a++>>>0];){var e=105!=c;e&=112!=c;b+=e&&b%8?4:0;Bc.push(112==c?y()[b>>>2>>>0]:106==c?M[b>>>3]:105==c?x()[b>>>2>>>0]:da()[b>>>3>>>0]);b+=e?8:4}return Bc};function zb(a,b,c){a>>>=0;b=Cc(b>>>0,c>>>0);return Vb[a](...b)}function Ab(a,b,c){a>>>=0;b=Cc(b>>>0,c>>>0);return Vb[a](...b)}var Bb=()=>{},Cb=()=>Date.now();function Db(a,b){return H(Q(a>>>0,b>>>0))}var Fb=()=>{U+=1;throw"unwind";};function Gb(){return 4294901760}var Hb;
Hb=()=>performance.timeOrigin+performance.now();var Ib=()=>C?require("os").cpus().length:navigator.hardwareConcurrency;function Jb(){P("Cannot use emscripten_pc_get_function without -sUSE_OFFSET_CONVERTER");return 0}
function Kb(a){a>>>=0;var b=t().length;if(a<=b||4294901760<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);var f=Math;e=Math.max(a,e);a:{f=(f.min.call(f,4294901760,e+(65536-e%65536)%65536)-k.buffer.byteLength+65535)/65536;try{k.grow(f);p();var g=1;break a}catch(h){}g=void 0}if(g)return!0}return!1}var Dc=()=>{P("Cannot use convertFrameToPC (needed by __builtin_return_address) without -sUSE_OFFSET_CONVERTER");return 0},X={},Ec=a=>{a.forEach(b=>{var c=Dc();c&&(X[c]=b)})};
function Lb(){var a=Error().stack.toString().split("\n");"Error"==a[0]&&a.shift();Ec(a);X.fb=Dc();X.qb=a;return X.fb}function Mb(a,b,c){a>>>=0;b>>>=0;if(X.fb==a)var e=X.qb;else e=Error().stack.toString().split("\n"),"Error"==e[0]&&e.shift(),Ec(e);for(var f=3;e[f]&&Dc()!=a;)++f;for(a=0;a<c&&e[a+f];++a)x()[b+4*a>>>2>>>0]=Dc();return a}
var Fc={},Hc=()=>{if(!Gc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:na||"./this.program"},b;for(b in Fc)void 0===Fc[b]?delete a[b]:a[b]=Fc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Gc=c}return Gc},Gc;
function Nb(a,b){if(D)return V(18,1,a,b);a>>>=0;b>>>=0;var c=0;Hc().forEach((e,f)=>{var g=b+c;f=y()[a+4*f>>>2>>>0]=g;for(g=0;g<e.length;++g)d()[f++>>>0]=e.charCodeAt(g);d()[f>>>0]=0;c+=e.length+1});return 0}function Ob(a,b){if(D)return V(19,1,a,b);a>>>=0;b>>>=0;var c=Hc();y()[a>>>2>>>0]=c.length;var e=0;c.forEach(f=>e+=f.length+1);y()[b>>>2>>>0]=e;return 0}function Qb(a){return D?V(20,1,a):52}function Rb(a,b,c,e){return D?V(21,1,a,b,c,e):52}function Sb(a,b,c,e){return D?V(22,1,a,b,c,e):70}
var Ic=[null,[],[]];function Tb(a,b,c,e){if(D)return V(23,1,a,b,c,e);b>>>=0;c>>>=0;e>>>=0;for(var f=0,g=0;g<c;g++){var h=y()[b>>>2>>>0],l=y()[b+4>>>2>>>0];b+=8;for(var n=0;n<l;n++){var q=t()[h+n>>>0],r=Ic[a];0===q||10===q?((1===a?va:H)(tc(r,0)),r.length=0):r.push(q)}f+=l}y()[e>>>2>>>0]=f;return 0}var Jc=a=>{try{a()}catch(b){P(b)}};
function Kc(){var a=Y,b={};for(let [c,e]of Object.entries(a))b[c]="function"==typeof e?(...f)=>{Lc.push(c);try{return e(...f)}finally{K||(Lc.pop(),E&&1===Z&&0===Lc.length&&(Z=0,U+=1,Jc(Mc),"undefined"!=typeof Fibers&&Fibers.yb()))}}:e;return b}var Z=0,E=null,Nc=0,Lc=[],Oc={},Pc={},Sc=0,Tc=null,Uc=[];function ka(){return new Promise((a,b)=>{Tc={resolve:a,reject:b}})}
function Vc(){var a=Wc(65548),b=a+12;y()[a>>>2>>>0]=b;y()[a+4>>>2>>>0]=b+65536;b=Lc[0];var c=Oc[b];void 0===c&&(c=Sc++,Oc[b]=c,Pc[c]=b);b=c;x()[a+8>>>2>>>0]=b;return a}function Xc(){var a=x()[E+8>>>2>>>0];a=Y[Pc[a]];--U;return a()}
function Yc(a){if(!K){if(0===Z){var b=!1,c=!1;a((e=0)=>{if(!K&&(Nc=e,b=!0,c)){Z=2;Jc(()=>Zc(E));"undefined"!=typeof Browser&&Browser.ab.hb&&Browser.ab.resume();e=!1;try{var f=Xc()}catch(l){f=l,e=!0}var g=!1;if(!E){var h=Tc;h&&(Tc=null,(e?h.reject:h.resolve)(f),g=!0)}if(e&&!g)throw f;}});c=!0;b||(Z=1,E=Vc(),"undefined"!=typeof Browser&&Browser.ab.hb&&Browser.ab.pause(),Jc(()=>$c(E)))}else 2===Z?(Z=0,Jc(ad),bd(E),E=null,Uc.forEach(uc)):P(`invalid state: ${Z}`);return Nc}}
function Wb(a){return Yc(b=>{a().then(b)})}D||hc();
var xc=[Ub,fc,rc,$a,ab,bb,cb,db,eb,fb,gb,hb,ib,jb,kb,lb,wb,xb,Nb,Ob,Qb,Rb,Sb,Tb],Va,Y=function(){function a(c,e){Y=c.exports;Y=Kc();Y=cd();gc.push(Y.Ga);La.unshift(Y.$);Ia=e;Oa();return Y}var b=za();N++;if(z.instantiateWasm)try{return z.instantiateWasm(b,a)}catch(c){H(`Module.instantiateWasm callback failed with error: ${c}`),A(c)}Qa||=z.locateFile?Pa("ort-wasm-simd-threaded.jsep.wasm")?"ort-wasm-simd-threaded.jsep.wasm":z.locateFile?z.locateFile("ort-wasm-simd-threaded.jsep.wasm",F):F+"ort-wasm-simd-threaded.jsep.wasm":
(new URL("ort-wasm-simd-threaded.jsep.wasm",import.meta.url)).href;Ua(b,function(c){a(c.instance,c.module)}).catch(A);return{}}();z._OrtInit=(a,b)=>(z._OrtInit=Y.aa)(a,b);z._OrtGetLastError=(a,b)=>(z._OrtGetLastError=Y.ba)(a,b);z._OrtCreateSessionOptions=(a,b,c,e,f,g,h,l,n,q)=>(z._OrtCreateSessionOptions=Y.ca)(a,b,c,e,f,g,h,l,n,q);z._OrtAppendExecutionProvider=(a,b)=>(z._OrtAppendExecutionProvider=Y.da)(a,b);
z._OrtAddFreeDimensionOverride=(a,b,c)=>(z._OrtAddFreeDimensionOverride=Y.ea)(a,b,c);z._OrtAddSessionConfigEntry=(a,b,c)=>(z._OrtAddSessionConfigEntry=Y.fa)(a,b,c);z._OrtReleaseSessionOptions=a=>(z._OrtReleaseSessionOptions=Y.ga)(a);z._OrtCreateSession=(a,b,c)=>(z._OrtCreateSession=Y.ha)(a,b,c);z._OrtReleaseSession=a=>(z._OrtReleaseSession=Y.ia)(a);z._OrtGetInputOutputCount=(a,b,c)=>(z._OrtGetInputOutputCount=Y.ja)(a,b,c);z._OrtGetInputName=(a,b)=>(z._OrtGetInputName=Y.ka)(a,b);
z._OrtGetOutputName=(a,b)=>(z._OrtGetOutputName=Y.la)(a,b);z._OrtFree=a=>(z._OrtFree=Y.ma)(a);z._OrtCreateTensor=(a,b,c,e,f,g)=>(z._OrtCreateTensor=Y.na)(a,b,c,e,f,g);z._OrtGetTensorData=(a,b,c,e,f)=>(z._OrtGetTensorData=Y.oa)(a,b,c,e,f);z._OrtReleaseTensor=a=>(z._OrtReleaseTensor=Y.pa)(a);z._OrtCreateRunOptions=(a,b,c,e)=>(z._OrtCreateRunOptions=Y.qa)(a,b,c,e);z._OrtAddRunConfigEntry=(a,b,c)=>(z._OrtAddRunConfigEntry=Y.ra)(a,b,c);z._OrtReleaseRunOptions=a=>(z._OrtReleaseRunOptions=Y.sa)(a);
z._OrtCreateBinding=a=>(z._OrtCreateBinding=Y.ta)(a);z._OrtBindInput=(a,b,c)=>(z._OrtBindInput=Y.ua)(a,b,c);z._OrtBindOutput=(a,b,c,e)=>(z._OrtBindOutput=Y.va)(a,b,c,e);z._OrtClearBoundOutputs=a=>(z._OrtClearBoundOutputs=Y.wa)(a);z._OrtReleaseBinding=a=>(z._OrtReleaseBinding=Y.xa)(a);z._OrtRunWithBinding=(a,b,c,e,f)=>(z._OrtRunWithBinding=Y.ya)(a,b,c,e,f);z._OrtRun=(a,b,c,e,f,g,h,l)=>(z._OrtRun=Y.za)(a,b,c,e,f,g,h,l);z._OrtEndProfiling=a=>(z._OrtEndProfiling=Y.Aa)(a);
z._JsepOutput=(a,b,c)=>(z._JsepOutput=Y.Ba)(a,b,c);z._JsepGetNodeName=a=>(z._JsepGetNodeName=Y.Ca)(a);
var I=()=>(I=Y.Da)(),Wc=z._malloc=a=>(Wc=z._malloc=Y.Ea)(a),bd=z._free=a=>(bd=z._free=Y.Fa)(a),Aa=(a,b,c,e,f,g)=>(Aa=Y.Ia)(a,b,c,e,f,g),Ha=()=>(Ha=Y.Ja)(),dc=(a,b,c,e,f)=>(dc=Y.Ka)(a,b,c,e,f),jc=a=>(jc=Y.La)(a),Fa=a=>(Fa=Y.Ma)(a),vc=()=>(vc=Y.Na)(),mc=(a,b)=>(mc=Y.Oa)(a,b),ec=a=>(ec=Y.Pa)(a),cc=a=>(cc=Y.Qa)(a),bc=()=>(bc=Y.Ra)(),nc=z.dynCall_ii=(a,b)=>(nc=z.dynCall_ii=Y.Ta)(a,b),$c=a=>($c=Y.Ua)(a),Mc=()=>(Mc=Y.Va)(),Zc=a=>(Zc=Y.Wa)(a),ad=()=>(ad=Y.Xa)();
function cd(){var a=Y;a=Object.assign({},a);var b=e=>()=>e()>>>0,c=e=>f=>e(f)>>>0;a.Da=b(a.Da);a.Ea=c(a.Ea);a.emscripten_main_runtime_thread_id=b(a.emscripten_main_runtime_thread_id);a.Qa=c(a.Qa);a.Ra=b(a.Ra);return a}z.stackSave=()=>bc();z.stackRestore=a=>ec(a);z.stackAlloc=a=>cc(a);z.UTF8ToString=Q;z.stringToUTF8=W;z.lengthBytesUTF8=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++c):b+=3}return b};var dd;
O=function ed(){dd||fd();dd||(O=ed)};function fd(){0<N||(D?(fa(z),D||lc(La),startWorker(z)):(lc(Ka),0<N||dd||(dd=!0,z.calledRun=!0,K||(D||lc(La),fa(z),D||lc(Ma)))))}fd();moduleRtn=ha;


  return moduleRtn;
}
);
})();
export default ortWasmThreaded;
var isPthread = globalThis.self?.name === 'em-pthread';
var isNode = typeof globalThis.process?.versions?.node == 'string';
if (isNode) isPthread = (await import('worker_threads')).workerData === 'em-pthread';

// When running as a pthread, construct a new instance on startup
isPthread && ortWasmThreaded();
